/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CAAIASysSprockets_h
#define CAAIASysSprockets_h

#ifndef ExportedByCAASysAutomationItf
#ifdef _WINDOWS_SOURCE
#ifdef __CAASysAutomationItf
#define ExportedByCAASysAutomationItf __declspec(dllexport)
#else
#define ExportedByCAASysAutomationItf __declspec(dllimport)
#endif
#else
#define ExportedByCAASysAutomationItf
#endif
#endif

#include "CATIACollection.h"
#include "CATSafeArray.h"
#include "CATVariant.h"

class CAAIASysSprocket;

extern ExportedByCAASysAutomationItf IID IID_CAAIASysSprockets;

class ExportedByCAASysAutomationItf CAAIASysSprockets : public CATIACollection
{
    CATDeclareInterface;

public:

    virtual HRESULT __stdcall Item(const CATVariant & iIndex, CAAIASysSprocket *& oSprocket)=0;

    virtual HRESULT __stdcall AddAll(const CATSafeArrayVariant & iSprocketArray)=0;

    virtual HRESULT __stdcall ToArray(CATSafeArrayVariant & ioArray)=0;


};

CATDeclareHandler(CAAIASysSprockets, CATIACollection);

#include "CAAIASysSprocket.h"
#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "CATIABase.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
