/*====================================================
 *  (c) 1999 Dassault Systemes. All rights reserved  =
 *     Generated by CNextBackEnd version 0.1 on      =
 *===================================================*/

#ifndef CAAIASysSprocket_h
#define CAAIASysSprocket_h

#ifndef ExportedByCAASysAutomationItf
#ifdef _WINDOWS_SOURCE
#ifdef __CAASysAutomationItf
#define ExportedByCAASysAutomationItf __declspec(dllexport)
#else
#define ExportedByCAASysAutomationItf __declspec(dllimport)
#endif
#else
#define ExportedByCAASysAutomationItf
#endif
#endif

#include "CATIABase.h"

extern ExportedByCAASysAutomationItf IID IID_CAAIASysSprocket;

class ExportedByCAASysAutomationItf CAAIASysSprocket : public CATIABase
{
    CATDeclareInterface;

public:

};

CATDeclareHandler(CAAIASysSprocket, CATIABase);

#include "CATBSTR.h"
#include "CATBaseDispatch.h"
#include "CATBaseUnknown.h"
#include "IDispatch.h"
#include "IUnknown.h"


#endif
